ALTER TABLE worker_profiles
    MODIFY COLUMN worker_type ENUM(
        'CATERING','CHEF','HEAD_CHEF','ASSISTANT_CHEF','COOK','BIRYANI_CHEF','TANDOOR_CHEF','SWEET_MITHAI_CHEF',
        'KITCHEN_HELPER','SERVING_STAFF','WAITER','CATERING_BOY','CATERING_GIRL','CLEANER','CATERING_SUPERVISOR',
        'EVENT_DECORATOR','WEDDING_DECORATOR','STAGE_DECORATOR','FLOWER_DECORATOR','BALLOON_DECORATOR','LIGHTING_TECHNICIAN',
        'TENT_SHAMIANA_WORKER','STAGE_SETUP_WORKER','MANDAP_DECORATOR','ENTRANCE_DECORATOR','BACKDROP_DECORATOR','DECORATION_SUPERVISOR',
        'DJ','SOUND_TECHNICIAN','SINGER','MALE_SINGER','FEMALE_SINGER','BAND_MEMBER','BAND_LEADER','MELAM_ARTIST',
        'BAND_MELAM_ARTIST','DANCER','DANCE_PERFORMER','DANCE_TROUPE','ANCHOR','MC','MAGICIAN','FOLK_ARTIST','CULTURAL_PERFORMER',
        'MAKEUP_ARTIST','BRIDAL_MAKEUP_ARTIST','GROOM_MAKEUP_ARTIST','HAIR_STYLIST','MEHENDI_ARTIST','SAREE_DRAPIST','BEAUTY_SPECIALIST',
        'PHOTOGRAPHER','WEDDING_PHOTOGRAPHER','EVENT_PHOTOGRAPHER','VIDEOGRAPHER','WEDDING_VIDEOGRAPHER','DRONE_OPERATOR',
        'PHOTO_EDITOR','VIDEO_EDITOR','PHOTO_BOOTH_OPERATOR','LIVE_STREAMING_OPERATOR',
        'PUJARI','PRIEST','PANDIT','POOJA_SPECIALIST','HOMAM_SPECIALIST','WEDDING_RITUAL_SPECIALIST',
        'EVENT_MANAGER','EVENT_SUPERVISOR','EVENT_COORDINATOR','HOST','REGISTRATION_STAFF','USHER','SECURITY_STAFF',
        'PARKING_STAFF','GENERAL_HELPER','CLEANING_STAFF',
        'CHAIR_RENTAL','TABLE_RENTAL','SOFA_RENTAL','CROCKERY_RENTAL','DINING_EQUIPMENT','COOKING_EQUIPMENT',
        'GENERATOR_OPERATOR','FAN_COOLER_RENTAL','TENT_RENTAL','STAGE_EQUIPMENT',
        'EVENT_DRIVER','GUEST_TRANSPORT_DRIVER','GOODS_TRANSPORT_DRIVER','LOADING_UNLOADING_STAFF',
        'INVITATION_DESIGNER','CAKE_SPECIALIST','RETURN_GIFT_SPECIALIST','CUSTOM_EVENT_PROFESSIONAL',
        'SERVING_BOY','SERVING_GIRL','SUPERVISOR','LIVE_STREAMER','BAND_MELAM','ANCHOR_EMCEE','KIDS_ENTERTAINER',
        'SAREE_DRAPER','NAIL_ARTIST','STAGE_TENT_SPECIALIST','SECURITY_GUARD','VALET_DRIVER'
    ) NOT NULL;

ALTER TABLE staffing_requests
    MODIFY COLUMN worker_type ENUM(
        'CATERING','CHEF','HEAD_CHEF','ASSISTANT_CHEF','COOK','BIRYANI_CHEF','TANDOOR_CHEF','SWEET_MITHAI_CHEF',
        'KITCHEN_HELPER','SERVING_STAFF','WAITER','CATERING_BOY','CATERING_GIRL','CLEANER','CATERING_SUPERVISOR',
        'EVENT_DECORATOR','WEDDING_DECORATOR','STAGE_DECORATOR','FLOWER_DECORATOR','BALLOON_DECORATOR','LIGHTING_TECHNICIAN',
        'TENT_SHAMIANA_WORKER','STAGE_SETUP_WORKER','MANDAP_DECORATOR','ENTRANCE_DECORATOR','BACKDROP_DECORATOR','DECORATION_SUPERVISOR',
        'DJ','SOUND_TECHNICIAN','SINGER','MALE_SINGER','FEMALE_SINGER','BAND_MEMBER','BAND_LEADER','MELAM_ARTIST',
        'BAND_MELAM_ARTIST','DANCER','DANCE_PERFORMER','DANCE_TROUPE','ANCHOR','MC','MAGICIAN','FOLK_ARTIST','CULTURAL_PERFORMER',
        'MAKEUP_ARTIST','BRIDAL_MAKEUP_ARTIST','GROOM_MAKEUP_ARTIST','HAIR_STYLIST','MEHENDI_ARTIST','SAREE_DRAPIST','BEAUTY_SPECIALIST',
        'PHOTOGRAPHER','WEDDING_PHOTOGRAPHER','EVENT_PHOTOGRAPHER','VIDEOGRAPHER','WEDDING_VIDEOGRAPHER','DRONE_OPERATOR',
        'PHOTO_EDITOR','VIDEO_EDITOR','PHOTO_BOOTH_OPERATOR','LIVE_STREAMING_OPERATOR',
        'PUJARI','PRIEST','PANDIT','POOJA_SPECIALIST','HOMAM_SPECIALIST','WEDDING_RITUAL_SPECIALIST',
        'EVENT_MANAGER','EVENT_SUPERVISOR','EVENT_COORDINATOR','HOST','REGISTRATION_STAFF','USHER','SECURITY_STAFF',
        'PARKING_STAFF','GENERAL_HELPER','CLEANING_STAFF',
        'CHAIR_RENTAL','TABLE_RENTAL','SOFA_RENTAL','CROCKERY_RENTAL','DINING_EQUIPMENT','COOKING_EQUIPMENT',
        'GENERATOR_OPERATOR','FAN_COOLER_RENTAL','TENT_RENTAL','STAGE_EQUIPMENT',
        'EVENT_DRIVER','GUEST_TRANSPORT_DRIVER','GOODS_TRANSPORT_DRIVER','LOADING_UNLOADING_STAFF',
        'INVITATION_DESIGNER','CAKE_SPECIALIST','RETURN_GIFT_SPECIALIST','CUSTOM_EVENT_PROFESSIONAL',
        'SERVING_BOY','SERVING_GIRL','SUPERVISOR','LIVE_STREAMER','BAND_MELAM','ANCHOR_EMCEE','KIDS_ENTERTAINER',
        'SAREE_DRAPER','NAIL_ARTIST','STAGE_TENT_SPECIALIST','SECURITY_GUARD','VALET_DRIVER'
    ) NOT NULL;

ALTER TABLE job_assignments
    MODIFY COLUMN worker_type ENUM(
        'CATERING','CHEF','HEAD_CHEF','ASSISTANT_CHEF','COOK','BIRYANI_CHEF','TANDOOR_CHEF','SWEET_MITHAI_CHEF',
        'KITCHEN_HELPER','SERVING_STAFF','WAITER','CATERING_BOY','CATERING_GIRL','CLEANER','CATERING_SUPERVISOR',
        'EVENT_DECORATOR','WEDDING_DECORATOR','STAGE_DECORATOR','FLOWER_DECORATOR','BALLOON_DECORATOR','LIGHTING_TECHNICIAN',
        'TENT_SHAMIANA_WORKER','STAGE_SETUP_WORKER','MANDAP_DECORATOR','ENTRANCE_DECORATOR','BACKDROP_DECORATOR','DECORATION_SUPERVISOR',
        'DJ','SOUND_TECHNICIAN','SINGER','MALE_SINGER','FEMALE_SINGER','BAND_MEMBER','BAND_LEADER','MELAM_ARTIST',
        'BAND_MELAM_ARTIST','DANCER','DANCE_PERFORMER','DANCE_TROUPE','ANCHOR','MC','MAGICIAN','FOLK_ARTIST','CULTURAL_PERFORMER',
        'MAKEUP_ARTIST','BRIDAL_MAKEUP_ARTIST','GROOM_MAKEUP_ARTIST','HAIR_STYLIST','MEHENDI_ARTIST','SAREE_DRAPIST','BEAUTY_SPECIALIST',
        'PHOTOGRAPHER','WEDDING_PHOTOGRAPHER','EVENT_PHOTOGRAPHER','VIDEOGRAPHER','WEDDING_VIDEOGRAPHER','DRONE_OPERATOR',
        'PHOTO_EDITOR','VIDEO_EDITOR','PHOTO_BOOTH_OPERATOR','LIVE_STREAMING_OPERATOR',
        'PUJARI','PRIEST','PANDIT','POOJA_SPECIALIST','HOMAM_SPECIALIST','WEDDING_RITUAL_SPECIALIST',
        'EVENT_MANAGER','EVENT_SUPERVISOR','EVENT_COORDINATOR','HOST','REGISTRATION_STAFF','USHER','SECURITY_STAFF',
        'PARKING_STAFF','GENERAL_HELPER','CLEANING_STAFF',
        'CHAIR_RENTAL','TABLE_RENTAL','SOFA_RENTAL','CROCKERY_RENTAL','DINING_EQUIPMENT','COOKING_EQUIPMENT',
        'GENERATOR_OPERATOR','FAN_COOLER_RENTAL','TENT_RENTAL','STAGE_EQUIPMENT',
        'EVENT_DRIVER','GUEST_TRANSPORT_DRIVER','GOODS_TRANSPORT_DRIVER','LOADING_UNLOADING_STAFF',
        'INVITATION_DESIGNER','CAKE_SPECIALIST','RETURN_GIFT_SPECIALIST','CUSTOM_EVENT_PROFESSIONAL',
        'SERVING_BOY','SERVING_GIRL','SUPERVISOR','LIVE_STREAMER','BAND_MELAM','ANCHOR_EMCEE','KIDS_ENTERTAINER',
        'SAREE_DRAPER','NAIL_ARTIST','STAGE_TENT_SPECIALIST','SECURITY_GUARD','VALET_DRIVER'
    ) NOT NULL;
