export const EVENT_TYPES = [
  'Birthday',
  'Wedding',
  'Engagement',
  'Reception',
  'Anniversary',
  'Baby Shower',
  'Naming Ceremony',
  'Housewarming',
  'Pooja / Religious Event',
  'Corporate Event',
  'School / College Event',
  'Festival',
  'Party',
  'Other',
]
